# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ten3roberts/NevronEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ten3roberts/NevronEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ten3roberts/NevronEngine/CMakeFiles /home/ten3roberts/NevronEngine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ten3roberts/NevronEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NevronEngine

# Build rule for target.
NevronEngine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NevronEngine
.PHONY : NevronEngine

# fast build rule for target.
NevronEngine/fast:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/build
.PHONY : NevronEngine/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f deps/glfw/CMakeFiles/uninstall.dir/build.make deps/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f deps/glfw/src/CMakeFiles/glfw.dir/build.make deps/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named glew_s

# Build rule for target.
glew_s: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glew_s
.PHONY : glew_s

# fast build rule for target.
glew_s/fast:
	$(MAKE) -f deps/glew/build/cmake/CMakeFiles/glew_s.dir/build.make deps/glew/build/cmake/CMakeFiles/glew_s.dir/build
.PHONY : glew_s/fast

#=============================================================================
# Target rules for targets named visualinfo

# Build rule for target.
visualinfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 visualinfo
.PHONY : visualinfo

# fast build rule for target.
visualinfo/fast:
	$(MAKE) -f deps/glew/build/cmake/CMakeFiles/visualinfo.dir/build.make deps/glew/build/cmake/CMakeFiles/visualinfo.dir/build
.PHONY : visualinfo/fast

#=============================================================================
# Target rules for targets named glew

# Build rule for target.
glew: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glew
.PHONY : glew

# fast build rule for target.
glew/fast:
	$(MAKE) -f deps/glew/build/cmake/CMakeFiles/glew.dir/build.make deps/glew/build/cmake/CMakeFiles/glew.dir/build
.PHONY : glew/fast

#=============================================================================
# Target rules for targets named glewinfo

# Build rule for target.
glewinfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glewinfo
.PHONY : glewinfo

# fast build rule for target.
glewinfo/fast:
	$(MAKE) -f deps/glew/build/cmake/CMakeFiles/glewinfo.dir/build.make deps/glew/build/cmake/CMakeFiles/glewinfo.dir/build
.PHONY : glewinfo/fast

Graphics/IndexBuffer.o: Graphics/IndexBuffer.cpp.o

.PHONY : Graphics/IndexBuffer.o

# target to build an object file
Graphics/IndexBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/IndexBuffer.cpp.o
.PHONY : Graphics/IndexBuffer.cpp.o

Graphics/IndexBuffer.i: Graphics/IndexBuffer.cpp.i

.PHONY : Graphics/IndexBuffer.i

# target to preprocess a source file
Graphics/IndexBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/IndexBuffer.cpp.i
.PHONY : Graphics/IndexBuffer.cpp.i

Graphics/IndexBuffer.s: Graphics/IndexBuffer.cpp.s

.PHONY : Graphics/IndexBuffer.s

# target to generate assembly for a file
Graphics/IndexBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/IndexBuffer.cpp.s
.PHONY : Graphics/IndexBuffer.cpp.s

Graphics/Material.o: Graphics/Material.cpp.o

.PHONY : Graphics/Material.o

# target to build an object file
Graphics/Material.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/Material.cpp.o
.PHONY : Graphics/Material.cpp.o

Graphics/Material.i: Graphics/Material.cpp.i

.PHONY : Graphics/Material.i

# target to preprocess a source file
Graphics/Material.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/Material.cpp.i
.PHONY : Graphics/Material.cpp.i

Graphics/Material.s: Graphics/Material.cpp.s

.PHONY : Graphics/Material.s

# target to generate assembly for a file
Graphics/Material.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/Material.cpp.s
.PHONY : Graphics/Material.cpp.s

Graphics/Model.o: Graphics/Model.cpp.o

.PHONY : Graphics/Model.o

# target to build an object file
Graphics/Model.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/Model.cpp.o
.PHONY : Graphics/Model.cpp.o

Graphics/Model.i: Graphics/Model.cpp.i

.PHONY : Graphics/Model.i

# target to preprocess a source file
Graphics/Model.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/Model.cpp.i
.PHONY : Graphics/Model.cpp.i

Graphics/Model.s: Graphics/Model.cpp.s

.PHONY : Graphics/Model.s

# target to generate assembly for a file
Graphics/Model.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/Model.cpp.s
.PHONY : Graphics/Model.cpp.s

Graphics/Renderer.o: Graphics/Renderer.cpp.o

.PHONY : Graphics/Renderer.o

# target to build an object file
Graphics/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/Renderer.cpp.o
.PHONY : Graphics/Renderer.cpp.o

Graphics/Renderer.i: Graphics/Renderer.cpp.i

.PHONY : Graphics/Renderer.i

# target to preprocess a source file
Graphics/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/Renderer.cpp.i
.PHONY : Graphics/Renderer.cpp.i

Graphics/Renderer.s: Graphics/Renderer.cpp.s

.PHONY : Graphics/Renderer.s

# target to generate assembly for a file
Graphics/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/Renderer.cpp.s
.PHONY : Graphics/Renderer.cpp.s

Graphics/Shader.o: Graphics/Shader.cpp.o

.PHONY : Graphics/Shader.o

# target to build an object file
Graphics/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/Shader.cpp.o
.PHONY : Graphics/Shader.cpp.o

Graphics/Shader.i: Graphics/Shader.cpp.i

.PHONY : Graphics/Shader.i

# target to preprocess a source file
Graphics/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/Shader.cpp.i
.PHONY : Graphics/Shader.cpp.i

Graphics/Shader.s: Graphics/Shader.cpp.s

.PHONY : Graphics/Shader.s

# target to generate assembly for a file
Graphics/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/Shader.cpp.s
.PHONY : Graphics/Shader.cpp.s

Graphics/Texture.o: Graphics/Texture.cpp.o

.PHONY : Graphics/Texture.o

# target to build an object file
Graphics/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/Texture.cpp.o
.PHONY : Graphics/Texture.cpp.o

Graphics/Texture.i: Graphics/Texture.cpp.i

.PHONY : Graphics/Texture.i

# target to preprocess a source file
Graphics/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/Texture.cpp.i
.PHONY : Graphics/Texture.cpp.i

Graphics/Texture.s: Graphics/Texture.cpp.s

.PHONY : Graphics/Texture.s

# target to generate assembly for a file
Graphics/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/Texture.cpp.s
.PHONY : Graphics/Texture.cpp.s

Graphics/UniformBuffer.o: Graphics/UniformBuffer.cpp.o

.PHONY : Graphics/UniformBuffer.o

# target to build an object file
Graphics/UniformBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/UniformBuffer.cpp.o
.PHONY : Graphics/UniformBuffer.cpp.o

Graphics/UniformBuffer.i: Graphics/UniformBuffer.cpp.i

.PHONY : Graphics/UniformBuffer.i

# target to preprocess a source file
Graphics/UniformBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/UniformBuffer.cpp.i
.PHONY : Graphics/UniformBuffer.cpp.i

Graphics/UniformBuffer.s: Graphics/UniformBuffer.cpp.s

.PHONY : Graphics/UniformBuffer.s

# target to generate assembly for a file
Graphics/UniformBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/UniformBuffer.cpp.s
.PHONY : Graphics/UniformBuffer.cpp.s

Graphics/VertexArray.o: Graphics/VertexArray.cpp.o

.PHONY : Graphics/VertexArray.o

# target to build an object file
Graphics/VertexArray.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/VertexArray.cpp.o
.PHONY : Graphics/VertexArray.cpp.o

Graphics/VertexArray.i: Graphics/VertexArray.cpp.i

.PHONY : Graphics/VertexArray.i

# target to preprocess a source file
Graphics/VertexArray.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/VertexArray.cpp.i
.PHONY : Graphics/VertexArray.cpp.i

Graphics/VertexArray.s: Graphics/VertexArray.cpp.s

.PHONY : Graphics/VertexArray.s

# target to generate assembly for a file
Graphics/VertexArray.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/VertexArray.cpp.s
.PHONY : Graphics/VertexArray.cpp.s

Graphics/VertexBuffer.o: Graphics/VertexBuffer.cpp.o

.PHONY : Graphics/VertexBuffer.o

# target to build an object file
Graphics/VertexBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/VertexBuffer.cpp.o
.PHONY : Graphics/VertexBuffer.cpp.o

Graphics/VertexBuffer.i: Graphics/VertexBuffer.cpp.i

.PHONY : Graphics/VertexBuffer.i

# target to preprocess a source file
Graphics/VertexBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/VertexBuffer.cpp.i
.PHONY : Graphics/VertexBuffer.cpp.i

Graphics/VertexBuffer.s: Graphics/VertexBuffer.cpp.s

.PHONY : Graphics/VertexBuffer.s

# target to generate assembly for a file
Graphics/VertexBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/VertexBuffer.cpp.s
.PHONY : Graphics/VertexBuffer.cpp.s

Graphics/VertexBufferLayout.o: Graphics/VertexBufferLayout.cpp.o

.PHONY : Graphics/VertexBufferLayout.o

# target to build an object file
Graphics/VertexBufferLayout.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/VertexBufferLayout.cpp.o
.PHONY : Graphics/VertexBufferLayout.cpp.o

Graphics/VertexBufferLayout.i: Graphics/VertexBufferLayout.cpp.i

.PHONY : Graphics/VertexBufferLayout.i

# target to preprocess a source file
Graphics/VertexBufferLayout.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/VertexBufferLayout.cpp.i
.PHONY : Graphics/VertexBufferLayout.cpp.i

Graphics/VertexBufferLayout.s: Graphics/VertexBufferLayout.cpp.s

.PHONY : Graphics/VertexBufferLayout.s

# target to generate assembly for a file
Graphics/VertexBufferLayout.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Graphics/VertexBufferLayout.cpp.s
.PHONY : Graphics/VertexBufferLayout.cpp.s

Math/Math.o: Math/Math.cpp.o

.PHONY : Math/Math.o

# target to build an object file
Math/Math.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Math.cpp.o
.PHONY : Math/Math.cpp.o

Math/Math.i: Math/Math.cpp.i

.PHONY : Math/Math.i

# target to preprocess a source file
Math/Math.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Math.cpp.i
.PHONY : Math/Math.cpp.i

Math/Math.s: Math/Math.cpp.s

.PHONY : Math/Math.s

# target to generate assembly for a file
Math/Math.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Math.cpp.s
.PHONY : Math/Math.cpp.s

Math/Matrix.o: Math/Matrix.cpp.o

.PHONY : Math/Matrix.o

# target to build an object file
Math/Matrix.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Matrix.cpp.o
.PHONY : Math/Matrix.cpp.o

Math/Matrix.i: Math/Matrix.cpp.i

.PHONY : Math/Matrix.i

# target to preprocess a source file
Math/Matrix.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Matrix.cpp.i
.PHONY : Math/Matrix.cpp.i

Math/Matrix.s: Math/Matrix.cpp.s

.PHONY : Math/Matrix.s

# target to generate assembly for a file
Math/Matrix.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Matrix.cpp.s
.PHONY : Math/Matrix.cpp.s

Math/Quaternion.o: Math/Quaternion.cpp.o

.PHONY : Math/Quaternion.o

# target to build an object file
Math/Quaternion.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Quaternion.cpp.o
.PHONY : Math/Quaternion.cpp.o

Math/Quaternion.i: Math/Quaternion.cpp.i

.PHONY : Math/Quaternion.i

# target to preprocess a source file
Math/Quaternion.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Quaternion.cpp.i
.PHONY : Math/Quaternion.cpp.i

Math/Quaternion.s: Math/Quaternion.cpp.s

.PHONY : Math/Quaternion.s

# target to generate assembly for a file
Math/Quaternion.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Quaternion.cpp.s
.PHONY : Math/Quaternion.cpp.s

Math/Vector.o: Math/Vector.cpp.o

.PHONY : Math/Vector.o

# target to build an object file
Math/Vector.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Vector.cpp.o
.PHONY : Math/Vector.cpp.o

Math/Vector.i: Math/Vector.cpp.i

.PHONY : Math/Vector.i

# target to preprocess a source file
Math/Vector.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Vector.cpp.i
.PHONY : Math/Vector.cpp.i

Math/Vector.s: Math/Vector.cpp.s

.PHONY : Math/Vector.s

# target to generate assembly for a file
Math/Vector.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Vector.cpp.s
.PHONY : Math/Vector.cpp.s

Math/Vector2.o: Math/Vector2.cpp.o

.PHONY : Math/Vector2.o

# target to build an object file
Math/Vector2.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Vector2.cpp.o
.PHONY : Math/Vector2.cpp.o

Math/Vector2.i: Math/Vector2.cpp.i

.PHONY : Math/Vector2.i

# target to preprocess a source file
Math/Vector2.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Vector2.cpp.i
.PHONY : Math/Vector2.cpp.i

Math/Vector2.s: Math/Vector2.cpp.s

.PHONY : Math/Vector2.s

# target to generate assembly for a file
Math/Vector2.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Vector2.cpp.s
.PHONY : Math/Vector2.cpp.s

Math/Vector3.o: Math/Vector3.cpp.o

.PHONY : Math/Vector3.o

# target to build an object file
Math/Vector3.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Vector3.cpp.o
.PHONY : Math/Vector3.cpp.o

Math/Vector3.i: Math/Vector3.cpp.i

.PHONY : Math/Vector3.i

# target to preprocess a source file
Math/Vector3.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Vector3.cpp.i
.PHONY : Math/Vector3.cpp.i

Math/Vector3.s: Math/Vector3.cpp.s

.PHONY : Math/Vector3.s

# target to generate assembly for a file
Math/Vector3.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Vector3.cpp.s
.PHONY : Math/Vector3.cpp.s

Math/Vector4.o: Math/Vector4.cpp.o

.PHONY : Math/Vector4.o

# target to build an object file
Math/Vector4.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Vector4.cpp.o
.PHONY : Math/Vector4.cpp.o

Math/Vector4.i: Math/Vector4.cpp.i

.PHONY : Math/Vector4.i

# target to preprocess a source file
Math/Vector4.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Vector4.cpp.i
.PHONY : Math/Vector4.cpp.i

Math/Vector4.s: Math/Vector4.cpp.s

.PHONY : Math/Vector4.s

# target to generate assembly for a file
Math/Vector4.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Math/Vector4.cpp.s
.PHONY : Math/Vector4.cpp.s

Scripts/Wave.o: Scripts/Wave.cpp.o

.PHONY : Scripts/Wave.o

# target to build an object file
Scripts/Wave.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Scripts/Wave.cpp.o
.PHONY : Scripts/Wave.cpp.o

Scripts/Wave.i: Scripts/Wave.cpp.i

.PHONY : Scripts/Wave.i

# target to preprocess a source file
Scripts/Wave.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Scripts/Wave.cpp.i
.PHONY : Scripts/Wave.cpp.i

Scripts/Wave.s: Scripts/Wave.cpp.s

.PHONY : Scripts/Wave.s

# target to generate assembly for a file
Scripts/Wave.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/Scripts/Wave.cpp.s
.PHONY : Scripts/Wave.cpp.s

src/Camera.o: src/Camera.cpp.o

.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i

.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s

.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Component.o: src/Component.cpp.o

.PHONY : src/Component.o

# target to build an object file
src/Component.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Component.cpp.o
.PHONY : src/Component.cpp.o

src/Component.i: src/Component.cpp.i

.PHONY : src/Component.i

# target to preprocess a source file
src/Component.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Component.cpp.i
.PHONY : src/Component.cpp.i

src/Component.s: src/Component.cpp.s

.PHONY : src/Component.s

# target to generate assembly for a file
src/Component.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Component.cpp.s
.PHONY : src/Component.cpp.s

src/Entity.o: src/Entity.cpp.o

.PHONY : src/Entity.o

# target to build an object file
src/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Entity.cpp.o
.PHONY : src/Entity.cpp.o

src/Entity.i: src/Entity.cpp.i

.PHONY : src/Entity.i

# target to preprocess a source file
src/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Entity.cpp.i
.PHONY : src/Entity.cpp.i

src/Entity.s: src/Entity.cpp.s

.PHONY : src/Entity.s

# target to generate assembly for a file
src/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Entity.cpp.s
.PHONY : src/Entity.cpp.s

src/GUID.o: src/GUID.cpp.o

.PHONY : src/GUID.o

# target to build an object file
src/GUID.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/GUID.cpp.o
.PHONY : src/GUID.cpp.o

src/GUID.i: src/GUID.cpp.i

.PHONY : src/GUID.i

# target to preprocess a source file
src/GUID.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/GUID.cpp.i
.PHONY : src/GUID.cpp.i

src/GUID.s: src/GUID.cpp.s

.PHONY : src/GUID.s

# target to generate assembly for a file
src/GUID.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/GUID.cpp.s
.PHONY : src/GUID.cpp.s

src/Logger.o: src/Logger.cpp.o

.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i

.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s

.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/ResourceManager.o: src/ResourceManager.cpp.o

.PHONY : src/ResourceManager.o

# target to build an object file
src/ResourceManager.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/ResourceManager.cpp.o
.PHONY : src/ResourceManager.cpp.o

src/ResourceManager.i: src/ResourceManager.cpp.i

.PHONY : src/ResourceManager.i

# target to preprocess a source file
src/ResourceManager.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/ResourceManager.cpp.i
.PHONY : src/ResourceManager.cpp.i

src/ResourceManager.s: src/ResourceManager.cpp.s

.PHONY : src/ResourceManager.s

# target to generate assembly for a file
src/ResourceManager.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/ResourceManager.cpp.s
.PHONY : src/ResourceManager.cpp.s

src/Rigidbody.o: src/Rigidbody.cpp.o

.PHONY : src/Rigidbody.o

# target to build an object file
src/Rigidbody.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Rigidbody.cpp.o
.PHONY : src/Rigidbody.cpp.o

src/Rigidbody.i: src/Rigidbody.cpp.i

.PHONY : src/Rigidbody.i

# target to preprocess a source file
src/Rigidbody.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Rigidbody.cpp.i
.PHONY : src/Rigidbody.cpp.i

src/Rigidbody.s: src/Rigidbody.cpp.s

.PHONY : src/Rigidbody.s

# target to generate assembly for a file
src/Rigidbody.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Rigidbody.cpp.s
.PHONY : src/Rigidbody.cpp.s

src/Settings.o: src/Settings.cpp.o

.PHONY : src/Settings.o

# target to build an object file
src/Settings.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Settings.cpp.o
.PHONY : src/Settings.cpp.o

src/Settings.i: src/Settings.cpp.i

.PHONY : src/Settings.i

# target to preprocess a source file
src/Settings.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Settings.cpp.i
.PHONY : src/Settings.cpp.i

src/Settings.s: src/Settings.cpp.s

.PHONY : src/Settings.s

# target to generate assembly for a file
src/Settings.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Settings.cpp.s
.PHONY : src/Settings.cpp.s

src/String.o: src/String.cpp.o

.PHONY : src/String.o

# target to build an object file
src/String.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/String.cpp.o
.PHONY : src/String.cpp.o

src/String.i: src/String.cpp.i

.PHONY : src/String.i

# target to preprocess a source file
src/String.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/String.cpp.i
.PHONY : src/String.cpp.i

src/String.s: src/String.cpp.s

.PHONY : src/String.s

# target to generate assembly for a file
src/String.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/String.cpp.s
.PHONY : src/String.cpp.s

src/Time.o: src/Time.cpp.o

.PHONY : src/Time.o

# target to build an object file
src/Time.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Time.cpp.o
.PHONY : src/Time.cpp.o

src/Time.i: src/Time.cpp.i

.PHONY : src/Time.i

# target to preprocess a source file
src/Time.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Time.cpp.i
.PHONY : src/Time.cpp.i

src/Time.s: src/Time.cpp.s

.PHONY : src/Time.s

# target to generate assembly for a file
src/Time.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Time.cpp.s
.PHONY : src/Time.cpp.s

src/Timer.o: src/Timer.cpp.o

.PHONY : src/Timer.o

# target to build an object file
src/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Timer.cpp.o
.PHONY : src/Timer.cpp.o

src/Timer.i: src/Timer.cpp.i

.PHONY : src/Timer.i

# target to preprocess a source file
src/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Timer.cpp.i
.PHONY : src/Timer.cpp.i

src/Timer.s: src/Timer.cpp.s

.PHONY : src/Timer.s

# target to generate assembly for a file
src/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Timer.cpp.s
.PHONY : src/Timer.cpp.s

src/Transform.o: src/Transform.cpp.o

.PHONY : src/Transform.o

# target to build an object file
src/Transform.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Transform.cpp.o
.PHONY : src/Transform.cpp.o

src/Transform.i: src/Transform.cpp.i

.PHONY : src/Transform.i

# target to preprocess a source file
src/Transform.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Transform.cpp.i
.PHONY : src/Transform.cpp.i

src/Transform.s: src/Transform.cpp.s

.PHONY : src/Transform.s

# target to generate assembly for a file
src/Transform.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Transform.cpp.s
.PHONY : src/Transform.cpp.s

src/Utility.o: src/Utility.cpp.o

.PHONY : src/Utility.o

# target to build an object file
src/Utility.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Utility.cpp.o
.PHONY : src/Utility.cpp.o

src/Utility.i: src/Utility.cpp.i

.PHONY : src/Utility.i

# target to preprocess a source file
src/Utility.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Utility.cpp.i
.PHONY : src/Utility.cpp.i

src/Utility.s: src/Utility.cpp.s

.PHONY : src/Utility.s

# target to generate assembly for a file
src/Utility.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/Utility.cpp.s
.PHONY : src/Utility.cpp.s

src/XMLParser.o: src/XMLParser.cpp.o

.PHONY : src/XMLParser.o

# target to build an object file
src/XMLParser.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/XMLParser.cpp.o
.PHONY : src/XMLParser.cpp.o

src/XMLParser.i: src/XMLParser.cpp.i

.PHONY : src/XMLParser.i

# target to preprocess a source file
src/XMLParser.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/XMLParser.cpp.i
.PHONY : src/XMLParser.cpp.i

src/XMLParser.s: src/XMLParser.cpp.s

.PHONY : src/XMLParser.s

# target to generate assembly for a file
src/XMLParser.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/XMLParser.cpp.s
.PHONY : src/XMLParser.cpp.s

src/pch.o: src/pch.cpp.o

.PHONY : src/pch.o

# target to build an object file
src/pch.cpp.o:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/pch.cpp.o
.PHONY : src/pch.cpp.o

src/pch.i: src/pch.cpp.i

.PHONY : src/pch.i

# target to preprocess a source file
src/pch.cpp.i:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/pch.cpp.i
.PHONY : src/pch.cpp.i

src/pch.s: src/pch.cpp.s

.PHONY : src/pch.s

# target to generate assembly for a file
src/pch.cpp.s:
	$(MAKE) -f CMakeFiles/NevronEngine.dir/build.make CMakeFiles/NevronEngine.dir/src/pch.cpp.s
.PHONY : src/pch.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... NevronEngine"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... glew_s"
	@echo "... visualinfo"
	@echo "... glew"
	@echo "... glewinfo"
	@echo "... Graphics/IndexBuffer.o"
	@echo "... Graphics/IndexBuffer.i"
	@echo "... Graphics/IndexBuffer.s"
	@echo "... Graphics/Material.o"
	@echo "... Graphics/Material.i"
	@echo "... Graphics/Material.s"
	@echo "... Graphics/Model.o"
	@echo "... Graphics/Model.i"
	@echo "... Graphics/Model.s"
	@echo "... Graphics/Renderer.o"
	@echo "... Graphics/Renderer.i"
	@echo "... Graphics/Renderer.s"
	@echo "... Graphics/Shader.o"
	@echo "... Graphics/Shader.i"
	@echo "... Graphics/Shader.s"
	@echo "... Graphics/Texture.o"
	@echo "... Graphics/Texture.i"
	@echo "... Graphics/Texture.s"
	@echo "... Graphics/UniformBuffer.o"
	@echo "... Graphics/UniformBuffer.i"
	@echo "... Graphics/UniformBuffer.s"
	@echo "... Graphics/VertexArray.o"
	@echo "... Graphics/VertexArray.i"
	@echo "... Graphics/VertexArray.s"
	@echo "... Graphics/VertexBuffer.o"
	@echo "... Graphics/VertexBuffer.i"
	@echo "... Graphics/VertexBuffer.s"
	@echo "... Graphics/VertexBufferLayout.o"
	@echo "... Graphics/VertexBufferLayout.i"
	@echo "... Graphics/VertexBufferLayout.s"
	@echo "... Math/Math.o"
	@echo "... Math/Math.i"
	@echo "... Math/Math.s"
	@echo "... Math/Matrix.o"
	@echo "... Math/Matrix.i"
	@echo "... Math/Matrix.s"
	@echo "... Math/Quaternion.o"
	@echo "... Math/Quaternion.i"
	@echo "... Math/Quaternion.s"
	@echo "... Math/Vector.o"
	@echo "... Math/Vector.i"
	@echo "... Math/Vector.s"
	@echo "... Math/Vector2.o"
	@echo "... Math/Vector2.i"
	@echo "... Math/Vector2.s"
	@echo "... Math/Vector3.o"
	@echo "... Math/Vector3.i"
	@echo "... Math/Vector3.s"
	@echo "... Math/Vector4.o"
	@echo "... Math/Vector4.i"
	@echo "... Math/Vector4.s"
	@echo "... Scripts/Wave.o"
	@echo "... Scripts/Wave.i"
	@echo "... Scripts/Wave.s"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Component.o"
	@echo "... src/Component.i"
	@echo "... src/Component.s"
	@echo "... src/Entity.o"
	@echo "... src/Entity.i"
	@echo "... src/Entity.s"
	@echo "... src/GUID.o"
	@echo "... src/GUID.i"
	@echo "... src/GUID.s"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/ResourceManager.o"
	@echo "... src/ResourceManager.i"
	@echo "... src/ResourceManager.s"
	@echo "... src/Rigidbody.o"
	@echo "... src/Rigidbody.i"
	@echo "... src/Rigidbody.s"
	@echo "... src/Settings.o"
	@echo "... src/Settings.i"
	@echo "... src/Settings.s"
	@echo "... src/String.o"
	@echo "... src/String.i"
	@echo "... src/String.s"
	@echo "... src/Time.o"
	@echo "... src/Time.i"
	@echo "... src/Time.s"
	@echo "... src/Timer.o"
	@echo "... src/Timer.i"
	@echo "... src/Timer.s"
	@echo "... src/Transform.o"
	@echo "... src/Transform.i"
	@echo "... src/Transform.s"
	@echo "... src/Utility.o"
	@echo "... src/Utility.i"
	@echo "... src/Utility.s"
	@echo "... src/XMLParser.o"
	@echo "... src/XMLParser.i"
	@echo "... src/XMLParser.s"
	@echo "... src/pch.o"
	@echo "... src/pch.i"
	@echo "... src/pch.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

